### ISSUE TITLE
StorageRef inside Pointer is almost useless.

### ISSUE THREAD

**Issue by vitvakatu** [kvark/froggy#25]
I suggest to replace it with some uid

**Comment by kvark** [comment]
Upon further inspection, it appears that you are right - it's not used for anything other than keeping the storage alive and verification. Since we can't do much without the storage anyway, we can replace the verification with some UID and be happy with it.

The change would have some far-fetching consequences, actually:
  1. faster `Pointer` creation/cloning, as well as storage locking
  2. no need for `StorageRef` with its `Arc<RwLock<Storage>>>` any more
  3. simpler `UpgradeErr`

**Comment by kvark** [comment]
Also please note that this issue is in direct conflict with #7
